# Generated by Django 2.1.7 on 2019-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190321_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
